FROM node:12-alpine

LABEL summary="UnblockNeteaseMusic NodeJS for ARM"
LABEL description="UnblockNeteaseMusic NodeJS for ARM devices"
LABEL maintainer="Zhou You <hi@zhouyou.info>"

ENTRYPOINT ["npx", "@nondanee/unblockneteasemusic"]
